# -*- coding: utf-8 -*-
"""TitanicVis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JC3x3Xt4Bbt4OZppR_8D8mBJ82OaU4_z

#Question 1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Titanic veri setini yükleyin
url = 'https://github.com/nazliyusufoglu/DataVisA2/raw/main/Titanic_dataset.xlsx'
df = pd.read_excel(url)

# NaN değerleri filtrele ve yaş sütununu seç
ages = df['age'].dropna()

# Alan grafiği oluştur
plt.figure(figsize=(10, 6))
sns.kdeplot(ages, fill=True, color='blue', edgecolor='black')
plt.title('Distribution of Ages of Titanic Passengers')
plt.xlabel('Age')
plt.ylabel('Density')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""# Question One Interactivity"""

import pandas as pd
import plotly.graph_objects as go
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

url = 'https://github.com/nazliyusufoglu/DataVisA2/raw/main/Titanic_dataset.xlsx'
df = pd.read_excel(url)


ages = df['age'].dropna()

# Seaborn kdeplot ile benzer bir grafiği çizin
plt.figure(figsize=(10, 6))
sns.kdeplot(ages, fill=True, color='skyblue', edgecolor='black')
plt.title('Distribution of Ages of Titanic Passengers')
plt.xlabel('Age')
plt.ylabel('Density')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Plotly ile benzer bir grafik çizin
fig = go.Figure()

fig.add_trace(go.Histogram(x=ages, nbinsx=30, histnorm='density', marker=dict(color='skyblue', line=dict(color='black', width=1))))

fig.update_layout(
    title='Distribution of Ages of Titanic Passengers',
    xaxis_title='Age',
    yaxis_title='Density'
)

fig.show()

"""#Question 2"""

import pandas as pd
import matplotlib.pyplot as plt


url = 'https://github.com/nazliyusufoglu/DataVisA2/raw/main/Titanic_dataset.xlsx'
df = pd.read_excel(url)

# Cinsiyet dağılımını hesapla
gender_distribution = df['sex'].value_counts()

# Pie chart çiz
plt.figure(figsize=(8, 8))
plt.pie(gender_distribution, labels=gender_distribution.index, autopct='%1.1f%%', colors=['skyblue', 'lightcoral'])
plt.title('Gender Distribution of Titanic Passengers')
plt.show()

"""# Question 3"""

import pandas as pd
import matplotlib.pyplot as plt


url = 'https://github.com/nazliyusufoglu/DataVisA2/raw/main/Titanic_dataset.xlsx'
df = pd.read_excel(url)

# Pclass (Passenger Class) dağılımını hesapla
pclass_distribution = df['pclass'].value_counts()

# Donut chart çiz
plt.figure(figsize=(8, 8))
plt.pie(pclass_distribution, labels=pclass_distribution.index, autopct='%1.1f%%', colors=['lightcoral', 'skyblue', 'lightgreen'], wedgeprops=dict(width=0.3))
plt.title('Passenger Class Distribution of Titanic Passengers')
plt.gca().add_artist(plt.Circle((0,0),0.2,fc='white'))
plt.show()

"""#Question 4"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url = 'https://github.com/nazliyusufoglu/DataVisA2/raw/main/Titanic_dataset.xlsx'
df = pd.read_excel(url)

# Cinsiyete göre yaş dağılımını görselleştirmek için bir viyolin grafiği oluşturma
plt.figure(figsize=(15, 10))
sns.violinplot(x='sex', y='age', data=df)
plt.title('Violin Plot of Age Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Age')
plt.show()

"""#Question Four Interactivity"""

import pandas as pd
import plotly.express as px

url = 'https://github.com/nazliyusufoglu/DataVisA2/raw/main/Titanic_dataset.xlsx'
df = pd.read_excel(url)
# Violin grafiği oluşturma ve interaktif olarak gösterme
fig = px.violin(df, x='sex', y='age', box=True, points="all", hover_data=df.columns)

# Grafik düzeni
fig.update_layout(
    title='Violin Plot of Age Distribution by Gender',
    xaxis_title='Gender',
    yaxis_title='Age',
    violinmode='overlay'
)
fig.show()

"""#Question 5"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url = 'https://github.com/nazliyusufoglu/DataVisA2/raw/main/Titanic_dataset.xlsx'

df = pd.read_excel(url)



plt.figure(figsize=[6, 12])
sns.countplot(x='sex', hue='survived', data=df)
plt.title('Number of people survived based on gender')
plt.xlabel('Gender (0: Male, 1: Female)')
plt.ylabel('Number of people survived')
plt.show()

"""# Question Five Interactivity"""

import pandas as pd
import plotly.express as px
from google.colab import files



url = 'https://github.com/nazliyusufoglu/DataVisA2/raw/main/Titanic_dataset.xlsx'
df = pd.read_excel(url)

fig = px.histogram(df, x='sex', color='survived', barmode='group',
                   labels={'sex': 'Gender', 'survived': 'Survived'},
                   title='Number of people survived based on gender',
                   hover_name='sex',
                   hover_data={'sex': False, 'survived': True},
                   category_orders={'sex': ['Male', 'Female'], 'survived': [0, 1]})

fig.show()